[package]
name = "rs_lib"
version = "0.0.0"
edition = "2021"

[lib]
crate_type = ["cdylib"]

[dependencies]
reqwest = "0.11.22"
rusty-s3 = { version = "0.5.0", features = ["wasm_bindgen"] }
wasm-bindgen = "=0.2.87"
